spec:
  inputs:
    sonar-quality-gate-enabled:
      description: 'Enables SonarQube [Quality Gate](https://docs.sonarsource.com/sonarqube-server/latest/quality-standards-administration/managing-quality-gates/introduction/) verification.'
      type: boolean
      default: false

---
# prevent duplicate pipelines
# https://docs.gitlab.com/ci/jobs/job_rules/#avoid-duplicate-pipelines
# https://docs.gitlab.com/ci/yaml/workflow/#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - build
  - test
#  - deploy
  - publish

include:
  - component: "$CI_SERVER_FQDN/zeta/zeta-ci-cd-components/container-scanning@v0.4.2"
    inputs:
      analyzer-image: "$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/aquasec/trivy:0.69.3@sha256:7228e304ae0f610a1fad937baa463598cadac0c2ac4027cc68f3a8b997115689"
      cs-image: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
      git-strategy: fetch
      severity: HIGH,CRITICAL
      job-stage: test
      openvex-file: "vulnerabilites.openvex.json"

default:
  image: $CI_REGISTRY/zeta/devops/ci-images/docker:24.0.5-zeta-0
  tags: [ zeta ]
  services:
    - name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker:25.0.5-dind
      alias: docker
      variables:
        HEALTHCHECK_TCP_PORT: "2376"

variables:
  DOCKER_BUILDKIT: "1"
  BUILDX_BUILDER: "ci-builder"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: $DOCKER_TLS_CERTDIR/client
  DOCKER_TLS_VERIFY: "1"
  BASE_IMAGE: "$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/nginxinc/nginx-unprivileged:$NGINX_VERSION-trixie-otel"
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

before_script:
  - docker context create docker
  - docker buildx create --name ci-builder --use --driver docker-container --driver-opt image="$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/moby/buildkit:buildx-stable-1" docker
  - docker buildx use ci-builder
  - printf "%s" "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login "$CI_DEPENDENCY_PROXY_SERVER" -u "$CI_DEPENDENCY_PROXY_USER" --password-stdin
  - printf "%s" "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

build:
  stage: build
  rules:
    # don't rebuild for nightly build, keep scanning the last-built image
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: always
  script:
    - |
      docker buildx build \
        --build-arg BUILDKIT_SYNTAX="$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX"/docker/dockerfile:1.7 \
        --cache-from type=registry,ref="$CI_REGISTRY_IMAGE:buildcache" \
        --cache-to type=registry,ref="$CI_REGISTRY_IMAGE:buildcache,mode=max,compression=zstd" \
        --tag "$IMAGE" \
        --push \
        "$@" \
        .

#trigger_helm:
#  stage: deploy
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "schedule"'
#      when: never
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
#      when: on_success
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#      when: on_success
#    - when: never
#  trigger:
#    project: zeta/devops/zeta-guard-helm
#    branch: main
#    strategy: depend
#  variables:
#    PROVISIONING_PROCESSOR_IMAGE_TAG: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" # e.g. main-cafebabe

tag_main:
  stage: publish
  rules:
    # don't trigger for nightly builds — they are supposed to check dependency issues in
    # *previously* built and released images, and not build/tag anything themselves.
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never
  needs:
    - job: build
      optional: true # resolved before rules are evaluated, which fails when schedule
#    - job: trigger_helm
#      optional: true
  script:
    - |
      export NEW_IMAGE="$CI_REGISTRY_IMAGE:$CI_DEFAULT_BRANCH"
      docker pull "$IMAGE"
      docker tag "$IMAGE" "$NEW_IMAGE"
      docker push "$NEW_IMAGE"
